### ISSUE TITLE
Default output without arguments

### ISSUE THREAD

**Issue by mmdevl** [matteocorti/vpn_eth#3]
Please add "init" to the default output without arguments:

```
./vpn_eth
==>
Error: Please specify a command (status, connect or disconnect)
```

should be:
```
Error: Please specify a command (status, connect, disconnect or init)
```

**Comment by matteocorti** [comment]
Fixed in [6226fb2](https://github.com/matteocorti/vpn_eth/commit/6226fb29a659d4cb56baa8981a61c014fb663e40)
